<a href="https://colab.research.google.com/github/TANU0208/2001921520062/blob/main/NumPy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr    #1 dimesional array

array([1, 2, 3, 4, 5])

In [5]:
arr.shape #it is a 1d array as it only represents rows

(5,)

In [7]:
MyList1 = [1,2,3,4,5]
MyList2 = [2,3,4,5,7]
MyList3 = [9,7,6,8,8]

Arr = np.array([MyList1, MyList2, MyList3])

In [9]:
Arr   #For 2 dimensional array we have 2 closing sq brackets and 2 opening brackets


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 7],
       [9, 7, 6, 8, 8]])

In [8]:
Arr.shape

(3, 5)

Arrays are generally used because the operations on arrays is very fast

In [10]:
Arr.reshape(5,3)  #the count of elements shoule be equal, here it is 5*3 = 15

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [7, 9, 7],
       [6, 8, 8]])

In [11]:
Arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 7, 9, 7, 6, 8, 8]])

**Indexing**

In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [13]:
arr[3]   #0 based indexing

4

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
Arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 7],
       [9, 7, 6, 8, 8]])